### ISSUE TITLE
Compiler error. What is the version of python? thank you

### ISSUE THREAD

**Issue by shihuajin111** [DonggeunYu/MEV-Attack-on-the-BSC#1]
python3
Python 3.9.6 (default, Oct 18 2022, 12:41:40)
[Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
My python version is 3.9

➜  MEV-Attack-Bot-on-the-BSC git:(main) python3 main_sandwich.py
Traceback (most recent call last):
  File "/Users/shihuajin/local/Desktop/work/MEV-Attack-Bot-on-the-BSC/main_sandwich.py", line 8, in <module>
    from src.apis.subscribe import stream_new_block_and_pending_txs, stream_new_future_accessible_block_number
  File "/Users/shihuajin/local/Desktop/work/MEV-Attack-Bot-on-the-BSC/src/apis/subscribe.py", line 11, in <module>
    from src.apis.trace_tx import trace_transaction
  File "/Users/shihuajin/local/Desktop/work/MEV-Attack-Bot-on-the-BSC/src/apis/trace_tx.py", line 9, in <module>
    from ..utils import get_provider, eq_address
  File "/Users/shihuajin/local/Desktop/work/MEV-Attack-Bot-on-the-BSC/src/utils.py", line 8, in <module>
    from web3.middleware import geth_poa_middleware
ImportError: cannot import name 'geth_poa_middleware' from 'web3.middleware' (/usr/local/lib/python3.9/site-packages/web3/middleware/__init__.py)

**Comment by DonggeunYu** [comment]
Thank you for your interest.

I remember it as python 3.11 version.
It worked in this Dockerfile environment.
https://github.com/DonggeunYu/MEV-Attack-Bot-on-the-BSC/blob/main/docker/node/bsc/Dockerfile
